apiVersion: v1
kind: Service
metadata:
  name: load-ants
  namespace: dns
  labels:
    app: load-ants
spec:
  selector:
    app: load-ants
  ports:
    - port: 53
      name: dns-udp
      protocol: UDP
      targetPort: 53
    - port: 53
      name: dns-tcp
      protocol: TCP
      targetPort: 53
    - port: 8080
      name: health
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
